### ISSUE TITLE
Bug - No document found after register

### ISSUE THREAD

**Issue by eidan66** [Saikai-oyo/Saikai#170]
## **Describe the bug**
We got an error after we register to the sytem.
```No document found! AuthContext.js:81:32```

## **To Reproduce**
1. Register via: Facebook / google / mail
2. then login to the application
3. will see only loading snipper.

## **Expected behavior**
See the dashboard

## **Screenshots**
![image](https://user-images.githubusercontent.com/41434778/120992488-524b9a00-c78b-11eb-80b4-03f4adf46c84.png)

**Comment by IdanEngel** [comment]
This bug is occurring ONLY with Firefox or Edge!
