### ISSUE TITLE
Feature - Responsive Login page

### ISSUE THREAD

**Issue by eidan66** [Saikai-oyo/Saikai#53]
# Responsive Login
When the UX/UI team will send us the responsive page, we will add it here.

**Comment by MatanForU** [comment]
# Responsive Login Page

<img width="366" alt="Screen Shot 2021-05-13 at 12 33 13" src="https://user-images.githubusercontent.com/8940907/118107419-63e98e00-b3e7-11eb-81c6-ab795d5c91d4.png">

**Comment by eidan66** [comment]
@MatanForU What about the text lines
 ```
Forgot password?
Need an account? Sign up
```
?
Do we hide them?
![image](https://user-images.githubusercontent.com/41434778/118415457-1f921280-b6b3-11eb-964b-3b2dcf53ffc3.png)

**Comment by eidan66** [comment]
# Updated image!

![Uploading image.png…]()

**Comment by eidan66** [comment]
Handle these issues on #117 PR.
Close.
