### ISSUE TITLE
Feature - Add Sign in & Sign Up with Facebook & Google

### ISSUE THREAD

**Issue by eidan66** [Saikai-oyo/Saikai#65]
# Auth with Facebook & Google
With Firebase we can add sign In & sign up with facebook & google.
Add the logic part to the component.

**Comment by MatanForU** [comment]
# Main Page Log in and Sign Up 
## with Facebook & Google Signs 

<img width="342" alt="Screen Shot 2021-05-13 at 11 54 24" src="https://user-images.githubusercontent.com/8940907/118102869-f8e98880-b3e1-11eb-9cd5-a7d7698253e8.png">
